# Generated by Django 3.2.4 on 2021-09-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=16, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefon'),
        ),
    ]
